name: flutter_cookie_consent
description: "Flutter Cookie Consent UI"
version: 1.0.0
homepage: https://github.com/redhotsixbull/flutter_cookie_consent
repository: https://github.com/redhotsixbull/flutter_cookie_consent.git
documentation: https://github.com/redhotsixbull/flutter_cookie_consent#readme
topics:
  - flutter
  - cookie
  - consent
  - gdpr
  - privacy

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.redhotsixbull.flutter_cookie_consent
        pluginClass: FlutterCookieConsentPlugin
      ios:
        pluginClass: FlutterCookieConsentPlugin
      web:
        pluginClass: FlutterCookieConsentWeb
        fileName: flutter_cookie_consent_web.dart